language: node_js
node_js:
  - node

cache:
  yarn: true
  directories:
    - node_modules

install: yarn install

script:
  - yarn lint
  - yarn flow
  - yarn test
  - yarn coverage
  - yarn build

before_deploy: yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: gh-pages
  local-dir: example/dist
  on:
    branch: master
